import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // Exact color tokens from the HTML design
      colors: {
        "surface-container-low": "#171b27",
        "primary-fixed": "#d9e2ff",
        "on-error": "#690005",
        "surface-container-lowest": "#0a0e19",
        "on-background": "#dfe2f2",
        "background": "#0f131e",
        "surface-bright": "#353945",
        "on-tertiary": "#00363d",
        "on-secondary-container": "#c0acff",
        "error-container": "#93000a",
        "primary-fixed-dim": "#b0c6ff",
        "outline": "#8c90a0",
        "secondary-container": "#5203d5",
        "on-primary-container": "#002661",
        "secondary": "#cdbdff",
        "secondary-fixed-dim": "#cdbdff",
        "surface-dim": "#0f131e",
        "on-tertiary-container": "#002f35",
        "on-tertiary-fixed": "#001f24",
        "inverse-on-surface": "#2c303c",
        "tertiary-container": "#009fb2",
        "surface-tint": "#b0c6ff",
        "on-secondary-fixed-variant": "#4f00d0",
        "surface-container-high": "#262a36",
        "on-primary-fixed-variant": "#00429b",
        "surface-container-highest": "#313441",
        "tertiary": "#00daf3",
        "on-primary": "#002d6e",
        "inverse-surface": "#dfe2f2",
        "on-tertiary-fixed-variant": "#004f58",
        "surface-container": "#1b1f2b",
        "on-surface": "#dfe2f2",
        "secondary-fixed": "#e8deff",
        "outline-variant": "#424655",
        "on-primary-fixed": "#001945",
        "surface": "#0f131e",
        "inverse-primary": "#0058ca",
        "on-secondary-fixed": "#20005f",
        "tertiary-fixed-dim": "#00daf3",
        "primary-container": "#558dff",
        "on-surface-variant": "#c2c6d7",
        "tertiary-fixed": "#9cf0ff",
        "primary": "#b0c6ff",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "surface-variant": "#313441",
        "on-secondary": "#370096",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
